### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by iteqla** [Amdromeda/Blocklist-Pi-Hole#1]
Hi,
I just downloaded this list and Pi-Hoe states that two domains are invalid:

  [i] Target: https://raw.githubusercontent.com/Amdromeda/Blocklist-Pi-Hole/master/Ads%20and%20trackers.txt
  [✓] Status: Retrieval successful
  [i] Received 687901 domains, 2 domains invalid!
      Sample of invalid domains:
      - srahah.eu
      - srahah.pl

I thought I'd let you know

**Comment by Amdromeda** [comment]
Hi, thanks for reporting the problem. It has been solved.
