### ISSUE TITLE
Legiit domain caught in the net

### ISSUE THREAD

**Issue by iteqla** [Amdromeda/Blocklist-Pi-Hole#3]
Hi,
These two domains are legit

 [which.co.uk](url) is a legit website that provides reviews on devices/home goods/service providers.
`pihole -q` returns:
Match found in https://raw.githubusercontent.com/Amdromeda/Blocklist-Pi-Hole/master/Ads%20and%20trackers.txt:
   logs.which.co.uk
   metrics.which.co.uk
   **_which.co.uk_**
 Match found in https://raw.githubusercontent.com/Amdromeda/Blocklist-Pi-Hole/master/Porn%20pages.txt:
   adultwhich.co.uk

cdnapisec.kaltura.com is needed to stream videos from [UK Parliament website](https://www.parliamentlive.tv/Commons)
`pihole -q` returns:
 Match found in https://raw.githubusercontent.com/Amdromeda/Blocklist-Pi-Hole/master/Ads%20and%20trackers.txt:
   **_cdnapisec.kaltura.com_**

**Comment by Amdromeda** [comment]
Fixed, thank you
