### ISSUE TITLE
Eraser is legit

### ISSUE THREAD

**Issue by iteqla** [Amdromeda/Blocklist-Pi-Hole#4]
Hi,
 [eraser.heidi.ie](url)  is the offcial website of Eraser, a software for erasing data at low level.
Would you be able to exclude it from the blacklist?

`pihole -q eraser.heidi.ie`
 Match found in https://raw.githubusercontent.com/Amdromeda/Blocklist-Pi-Hole/master/Porn%20pages.txt:
   eraser.heidi.ie

**Comment by Amdromeda** [comment]
Fixed, thank you
